language: en
pipeline: supervised_embeddings
policies:
- core_threshold: 0.3
  fallback_action_name: action_default_fallback
  name: FallbackPolicy
  nlu_threshold: 0.4
- name: MemoizationPolicy
- name: KerasPolicy
- name: MappingPolicy
